# To create an environment from this file, run the following command:
# $ conda env create -p /path/to/env/env-name -f "environment.yml"
#
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.14
  - numpy
  - pandas
  - scipy
  - h5py
  - pyarrow
  - openpyxl
  - pytest
  - pytest-xdist
  - pytest-html
  - progressbar2
  - matplotlib
  - papermill
  - python-dotenv
  - notebook
  - ipywidgets
  - ipympl
  - pyhdf
  - gatiab
  - geoclide
  - statsmodels
  - pip
  - pip:
    - pycuda
    - git+https://github.com/hygeos/luts.git
    - hitran-api
    - jax[cuda12]