# To create an environment from this file, run the following command:
# $ conda env create -p /path/to/env/env-name -f "environment.yml"
#
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.14
  - numpy>=2
  - pandas
  - scipy
  - h5py
  - pyarrow
  - openpyxl
  - pytest
  - pytest-xdist
  - pytest-html
  - progressbar2
  - matplotlib
  - papermill
  - python-dotenv
  - notebook
  - ipywidgets
  - ipympl
  - pyhdf
  - gatiab>=1.1.1
  - geoclide
  - statsmodels
  - luts
  - pytrunc
  - pip
  - pip:
    - pycuda
    - jax[cuda12]>=0.4
    - radis>=0.17
    - hitran-api>=1.1