# To create an environment from this file, run the following command:
# $ conda env create -p /path/to/env/env-name -f "environment.yml"
#
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - numpy>=2
  - xarray
  - pandas
  - scipy
  - h5py
  - pyarrow
  - openpyxl
  - pytest
  - pytest-xdist
  - pytest-html
  - progressbar2
  - matplotlib
  - papermill
  - python-dotenv
  - notebook
  - jupytext>=1.16
  - ipywidgets
  - ipympl
  - pyhdf
  - geoclide>=4.0.0
  - luts
  - pytrunc>=2.0.0
  - pip
  - gatiab>=1.1.2
  - pip:
    - pycuda
